FROM alpine:3.15.0
LABEL version="1.0.0" maintainer="Aoulia Lhaloui" os="alpine" distro="stro"
ENV CONTAINER_USER "Aoulia"
RUN adduser -S -D $CONTAINER_USER
USER $CONTAINER_USER
CMD echo  "hello-alpine, I’m Aoulia and this is a container from my first image"